Logrotate
pureelk/pureelk pull request #13
Opened 2017-01-11 20:31 UTC by clai-ps

Add logrotate. Default is 5 copies of 20Mb each for each log files.

2017-01-26 22:06 UTC, gary-yang commented on pureelk.sh
> +        -e "LOGS_DIRECTORIES=/var/lib/docker/containers /var/log/pureelk" \
Should you also set LOGROTATE_COPIES to a fix number? Otherwise wouldn't we still keep the log files forever?

2017-01-26 22:06 UTC, gary-yang requested changes
Looks like we should add LOGROTATE_COPIES setting as well.

2017-01-27 03:21 UTC, clai-ps commented
I believe no. Default is 5 copies.

Eric

On Thu, Jan 26, 2017 at 2:06 PM, Gary Yang <notifications@github.com> wrote:

> *@gary-yang* requested changes on this pull request.
>
> Looks like we should add LOGROTATE_COPIES setting as well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pureelk/pureelk/pull/13#pullrequestreview-18736075>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXWgh4hFaqxbTMxom6lzvT2U7DPXvvAeks5rWRj0gaJpZM4LhCLE>
> .
>

2017-01-27 03:45 UTC, clai-ps commented
This is what I got from my testing:

clai@vm-clai2:/var/log/pureelk$ ls -lh

total 281M

-rw-r--r-- 1 root root 1.9M Jan 26 19:45 array-tasks.log

-rw-r--r-- 1 root root  21M Jan 26 19:43 array-tasks.log.1

-rw-r--r-- 1 root root  21M Jan 26 19:21 array-tasks.log.2

-rw-r--r-- 1 root root  21M Jan 26 19:00 array-tasks.log.3

-rw-r--r-- 1 root root  21M Jan 26 18:39 array-tasks.log.4

-rw-r--r-- 1 root root  21M Jan 26 18:18 array-tasks.log.5

-rw-r--r-- 1 root root  21M Jan 26 17:55 array-tasks.log.6

-rw-r--r-- 1 root root 5.0M Jan 12 11:58 rest.log

-rw-r--r-- 1 root root  20M Jan 11 13:39 rest.log.1

-rw-r--r-- 1 root root 5.8K Jan 10 09:53 rest.log.2

-rw-r--r-- 1 root root 5.8K Jan 10 09:53 rest.log.3

-rw-r--r-- 1 root root 5.8K Jan 10 09:52 rest.log.4

-rw-r--r-- 1 root root 5.8K Jan 10 09:52 rest.log.5

-rw-r--r-- 1 root root 5.8K Jan 10 09:52 rest.log.6

-rw-r--r-- 1 root root  14M Jan 26 19:45 scheduler.log

-rw-r--r-- 1 root root  21M Jan 26 15:32 scheduler.log.1

-rw-r--r-- 1 root root  21M Jan 26 09:16 scheduler.log.2

-rw-r--r-- 1 root root  21M Jan 26 02:59 scheduler.log.3

-rw-r--r-- 1 root root  21M Jan 25 20:43 scheduler.log.4

-rw-r--r-- 1 root root  21M Jan 25 14:26 scheduler.log.5

-rw-r--r-- 1 root root  21M Jan 25 08:10 scheduler.log.6

clai@vm-clai2:/var/log/pureelk$




On Thu, Jan 26, 2017 at 7:21 PM, Eric Lai <clai@purestorage.com> wrote:

> I believe no. Default is 5 copies.
>
> Eric
>
> On Thu, Jan 26, 2017 at 2:06 PM, Gary Yang <notifications@github.com>
> wrote:
>
>> *@gary-yang* requested changes on this pull request.
>>
>> Looks like we should add LOGROTATE_COPIES setting as well.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pureelk/pureelk/pull/13#pullrequestreview-18736075>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AXWgh4hFaqxbTMxom6lzvT2U7DPXvvAeks5rWRj0gaJpZM4LhCLE>
>> .
>>
>
>

2017-01-27 17:12 UTC, clai-ps commented on pureelk.sh
> +        -e "LOGS_DIRECTORIES=/var/lib/docker/containers /var/log/pureelk" \
We don't need to set it. Default is 5. This is the documentation:
https://github.com/blacklabelops/logrotate/blob/master/README.md

I have tested in my local with the output in the other thread.

2017-01-30 17:31 UTC, gary-yang commented
Got it. I ran the container over the weekend. It worked. I'll suggest we specify 10 copies. It stores  about 12 hours of array-tasks.log.

2017-01-30 18:18 UTC, clai-ps commented
Hum. But it depends on the number of array that is registered. If you have
a lot of array, it will be less than 12 hours. I can change to 10 if you
think that is the best.

Eric

On Mon, Jan 30, 2017 at 9:31 AM, Gary Yang <notifications@github.com> wrote:

> Got it. I ran the container over the weekend. It worked. I'll suggest we
> specify 10 copies. It stores about 12 hours of array-tasks.log.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pureelk/pureelk/pull/13#issuecomment-276129192>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AXWgh9wExjOF1QUxNd7VlQEY5-fQo3FJks5rXh5-gaJpZM4LhCLE>
> .
>

2017-01-30 18:21 UTC, gary-yang commented
Yes, it will depend on the # of arrays. 10 copies is for 12 hours for 1 array in my experiment.

2017-01-30 18:21 UTC, clai-ps commented
Or we can set it to 40Mb each file instead of 20Mb. That would have the
same effect.

Eric

On Mon, Jan 30, 2017 at 10:18 AM, Eric Lai <clai@purestorage.com> wrote:

> Hum. But it depends on the number of array that is registered. If you have
> a lot of array, it will be less than 12 hours. I can change to 10 if you
> think that is the best.
>
> Eric
>
> On Mon, Jan 30, 2017 at 9:31 AM, Gary Yang <notifications@github.com>
> wrote:
>
>> Got it. I ran the container over the weekend. It worked. I'll suggest we
>> specify 10 copies. It stores about 12 hours of array-tasks.log.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pureelk/pureelk/pull/13#issuecomment-276129192>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AXWgh9wExjOF1QUxNd7VlQEY5-fQo3FJks5rXh5-gaJpZM4LhCLE>
>> .
>>
>
>

2017-01-30 18:36 UTC, clai-ps commented
Updated.

On Mon, Jan 30, 2017 at 10:21 AM, Gary Yang <notifications@github.com>
wrote:

> Yes, it will depend on the # of arrays. 10 copies is for 12 hours for 1
> array in my experiment.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pureelk/pureelk/pull/13#issuecomment-276145719>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AXWgh_R7vsuGOhBoY5F7t1XcryrsWQffks5rXipAgaJpZM4LhCLE>
> .
>

2017-01-30 19:59 UTC, merged